{
 "title": "Ortosat Outbound Traffic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Tráfegos NRT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tráfego 1 Minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.service.responses.bytes.total",
     "query": "SELECT sum(\"count\") FROM \"traefik.service.responses.bytes.total\" WHERE (\"service\"::tag = 'webdav@docker') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=", "value": "webdav@docker" }
     ]
    }
   ]
  },
  {
   "title": "Tráfego Cumulativo Diário",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "SELECT sum(\"count\") as traffic \nFROM \"traefik.service.responses.bytes.total\" \nWHERE (\"service\"::tag = 'webdav@docker') AND $timeFilter\nGROUP BY time(1d)\n"
    }
   ]
  },
  {
   "title": "Tráfego 1h",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"count\") FROM \"traefik.service.responses.bytes.total\" WHERE (\"service\"::tag = 'webdav@docker') AND $timeFilter GROUP BY time(1h) fill(null)"
    }
   ]
  },
  {
   "title": "Tráfego Cumulativo Mensal",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "SELECT sum(\"count\") as traffic \nFROM \"traefik.service.responses.bytes.total\" \nWHERE (\"service\"::tag = 'webdav@docker') AND $timeFilter\nGROUP BY time(30d)\n"
    }
   ]
  }
 ]
}