{
 "title": "Traefik Metrics",
 "description": "Traefik metrics from Influxdb database",
 "tags": [ "www" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backend",
    "label": "Backend",
    "query": "select * from \"traefik.backend.requests.total\""
   },
   { "name": "sampling", "label": "Sampling", "query": "1m,10m,60m" }
  ]
 },
 "panels": [
  {
   "title": "Total request",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "traefik.entrypoint.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total status code count",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 2, "y": 0 },
   "targets": [
    {
     "alias": "$tag_code",
     "groupBy": [
      { "params": [ "code" ], "type": "tag" }
     ],
     "measurement": "traefik.entrypoint.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "service::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "traefik.service.request.duration",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Access by backends",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "service::tag" ], "type": "tag" }
     ],
     "measurement": "traefik.service.requests.total",
     "query": "SELECT sum(\"count\") FROM \"traefik.service.requests.total\" WHERE $timeFilter GROUP BY time($sampling), \"service\"::tag",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}